# Copyright (C) 2024 In-Game Event, A Red Flag Syndicate LLC
#
# This program is free software: you can redistribute it and/or modify it under the terms of the Server Side Public License, version 1, as published by MongoDB, Inc., with the following additional terms:
#
# - Any use of this software in a commercial capacity requires a commercial license agreement with In-Game Event, A Red Flag Syndicate LLC. Contact licence_request@igearfs.com for details.
#
# - If you choose not to obtain a commercial license, you must comply with the SSPL terms, which include making publicly available the source code for all programs, tooling, and infrastructure used to operate this software as a service.
#
# For licensing inquiries, contact: licence_request@igearfs.com

services:

  # Citus Master Node (PostgreSQL)
  mc-citusdata-postgres-master:
    build:
      context: .
      dockerfile: postgres.Dockerfile  # Uses the custom Dockerfile based on Citus
    container_name: mc-citusdata-postgres-master
    expose:
      - "5432"
    labels:
      - "com.citusdata.role=Master"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MC1_DATABASE=${MC1_DATABASE}
      - MC2_DATABASE=${MC2_DATABASE}
      - MC1_DATABASE_USERNAME=${MC1_DATABASE_USERNAME}
      - MC1_DATABASE_PASSWORD=${MC1_DATABASE_PASSWORD}
      - MC2_DATABASE_USERNAME=${MC2_DATABASE_USERNAME}
      - MC2_DATABASE_PASSWORD=${MC2_DATABASE_PASSWORD}
    volumes:
      - mc-citusdata-postgres-master-data:/var/lib/postgresql/data
    networks:
      - mc-network

  # Mirth Connect Service 1
  mc-connect-1:
    image: nextgenhealthcare/connect:4.5.2
    container_name: mc-connect-1
    user: "1000:1000"
    env_file:
      - .env
    entrypoint: [ "/usr/local/bin/wait-for-it.sh", "mc-citusdata-postgres-master:5432", "--", "./mcserver"]
    environment:
      - DATABASE=${MC1_DATABASE_TYPE}
      - DATABASE_URL=${MC1_DATABASE_URL}
      - DATABASE_USERNAME=${MC1_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${MC1_DATABASE_PASSWORD}
      - KEYSTORE_STOREPASS=${MC1_KEYSTORE_STOREPASS}
      - KEYSTORE_KEYPASS=${MC1_KEYSTORE_KEYPASS}
      - VMOPTIONS=${MC1_VMOPTIONS}
    ports:
      - "8443:8443"
    volumes:
      - ./startup_files/scripts/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./startup_files/certificates-to-load-into-mc:/opt/connect/certificates-to-load-into-mc:rw
      - mc-connect-1-appdata:/opt/connect/appdata
      - mc-connect-1-custom-extensions:/opt/connect/custom-extensions
      - mc-connect-1-custom-lib:/opt/connect/custom-lib
      - ./startup_files/scripts/load_certs.sh:/opt/connect/load_certs.sh:rwx
    networks:
      - mc-network
    depends_on:
      - mc-citusdata-postgres-master

  # Mirth Connect Service 2
  mc-connect-2:
    image: nextgenhealthcare/connect:4.5.2
    container_name: mc-connect-2
    user: "1000:1000"
    env_file:
      - .env
    entrypoint: [ "/usr/local/bin/wait-for-it.sh", "mc-citusdata-postgres-master:5432", "--", "./mcserver"]
    environment:
      - DATABASE=${MC2_DATABASE_TYPE}
      - DATABASE_URL=${MC2_DATABASE_URL}
      - DATABASE_USERNAME=${MC2_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${MC2_DATABASE_PASSWORD}
      - KEYSTORE_STOREPASS=${MC2_KEYSTORE_STOREPASS}
      - KEYSTORE_KEYPASS=${MC2_KEYSTORE_KEYPASS}
      - VMOPTIONS=${MC2_VMOPTIONS}
    ports:
      - "8444:8443"
    volumes:
      - ./startup_files/scripts/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./startup_files/certificates-to-load-into-mc:/opt/connect/certificates-to-load-into-mc:rw
      - mc-connect-2-appdata:/opt/connect/appdata
      - mc-connect-2-custom-extensions:/opt/connect/custom-extensions
      - mc-connect-2-custom-lib:/opt/connect/custom-lib
      - ./startup_files/scripts/load_certs.sh:/opt/connect/load_certs.sh:rwx
    networks:
      - mc-network
    depends_on:
      - mc-citusdata-postgres-master
      - mc-connect-1

  # Stunnel Service for SSL Termination
  mc-stunnel:
    build:
      context: .
      dockerfile: stunnel.Dockerfile
    container_name: mc-stunnel-container
    ports:
      - "${STUNNEL_PORT}:${STUNNEL_PORT}"
    volumes:
      - ./stunnel.conf:/etc/stunnel/stunnel.conf
      - ./stunnel_certs/server:/etc/stunnel/certs
    networks:
      - mc-network
    depends_on:
      - mc-connect-1
      - mc-connect-2
      - mc-haproxy

  # HAProxy for Load Balancing
  mc-haproxy:
    image: haproxy:2.4
    container_name: mc-haproxy-container
    expose:
      - "${HAPROXY_PORT_1}"
      - "${HAPROXY_PORT_2}"
      - "${HAPROXY_PORT_3}"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - mc-network
    depends_on:
      - mc-connect-1
      - mc-connect-2

  # pgAdmin for PostgreSQL Management
  mc-pgadmin:
    image: dpage/pgadmin4
    container_name: mc-pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - mc-pgadmin-data:/var/lib/pgadmin
    networks:
      - mc-network
    depends_on:
      - mc-citusdata-postgres-master

volumes:
  mc-citusdata-postgres-master-data:
    driver: local
    driver_opts:
      type: none
      device: ./mc/mc-citusdata-postgres-master-data
      o: bind

  mc-pgadmin-data:
    driver: local
    driver_opts:
      type: none
      device: ./mc/mc-pgadmin-data
      o: bind

  mc-connect-1-appdata:
    driver: local
    driver_opts:
      type: none
      device: ./mc/mc-connect-1-appdata
      o: bind

  mc-connect-1-custom-extensions:
    driver: local
    driver_opts:
      type: none
      device: ./mc/mc-connect-1-custom-extensions
      o: bind

  mc-connect-1-custom-lib:
    driver: local
    driver_opts:
      type: none
      device: ./mc/mc-connect-1-custom-lib
      o: bind

  mc-connect-2-appdata:
    driver: local
    driver_opts:
      type: none
      device: ./mc/mc-connect-2-appdata
      o: bind

  mc-connect-2-custom-extensions:
    driver: local
    driver_opts:
      type: none
      device: ./mc/mc-connect-2-custom-extensions
      o: bind

  mc-connect-2-custom-lib:
    driver: local
    driver_opts:
      type: none
      device: ./mc/mc-connect-2-custom-lib
      o: bind

networks:
  mc-network:
    driver: bridge
