# Copyright (C) 2024 In-Game Event, A Red Flag Syndicate LLC
#
# This program is free software: you can redistribute it and/or modify it under the terms of the Server Side Public License, version 1, as published by MongoDB, Inc., with the following additional terms:
#
# - Any use of this software in a commercial capacity requires a commercial license agreement with In-Game Event, A Red Flag Syndicate LLC. Contact licence_request@igearfs.com for details.
#
# - If you choose not to obtain a commercial license, you must comply with the SSPL terms, which include making publicly available the source code for all programs, tooling, and infrastructure used to operate this software as a service.
#
# For licensing inquiries, contact: licence_request@igearfs.com

services:
  # Mirth Connect Service 1
  mc-connect-1:
    image: nextgenhealthcare/connect:4.5.2
    container_name: mc-connect-1
    user: "1000:1000"
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://mc-citusdata-postgres-master:5432/mirthdb1?currentSchema=mirthdb1
      - DATABASE_USERNAME=mirthuser1
      - DATABASE_PASSWORD=mirthpassword1
      - KEYSTORE_STOREPASS=changeme
      - KEYSTORE_KEYPASS=changeme
      - VMOPTIONS=-Xmx512m
    ports:
      - "8443:8443"
    volumes:
      - ./startup_files/certificates-to-load-into-mc:/opt/connect/certificates-to-load-into-mc:rw
      - ./mc/mc-connect-1-appdata:/opt/connect/appdata
      - ./mc/mc-connect-1-custom-extensions:/opt/connect/custom-extensions
      - ./mc/mc-connect-1-custom-lib:/opt/connect/custom-lib
      - ./startup_files/scripts/load_certs.sh:/opt/connect/load_certs.sh:rwx
    networks:
      - mc-network
    depends_on:
      - mc-citusdata-postgres-master

  # Mirth Connect Service 2
  mc-connect-2:
    image: nextgenhealthcare/connect:4.5.2
    container_name: mc-connect-2
    user: "1000:1000"
    environment:
      - DATABASE=postgres
      - DATABASE_URL=jdbc:postgresql://mc-citusdata-postgres-master:5432/mirthdb2?currentSchema=mirthdb2
      - DATABASE_USERNAME=mirthuser2
      - DATABASE_PASSWORD=mirthpassword2
      - KEYSTORE_STOREPASS=changeme
      - KEYSTORE_KEYPASS=changeme
      - VMOPTIONS=-Xmx512m
    ports:
      - "8444:8443"
    volumes:
      - ./startup_files/certificates-to-load-into-mc:/opt/connect/certificates-to-load-into-mc:rw
      - ./mc/mc-connect-2-appdata:/opt/connect/appdata
      - ./mc/mc-connect-2-custom-extensions:/opt/connect/custom-extensions
      - ./mc/mc-connect-2-custom-lib:/opt/connect/custom-lib
      - ./startup_files/scripts/load_certs.sh:/opt/connect/load_certs.sh:rwx
    networks:
      - mc-network
    depends_on:
      - mc-citusdata-postgres-master

  # Stunnel Service for SSL Termination
  mc-stunnel:
    build:
      context: .  # Build from the stunnel.Dockerfile in the current directory
      dockerfile: stunnel.Dockerfile
    container_name: mc-stunnel-container
    ports:
      - "6666:6666"
    volumes:
      - ./stunnel.conf:/etc/stunnel/stunnel.conf
      - ./stunnel_certs/server:/etc/stunnel/certs
    networks:
      - mc-network
    depends_on:
      - mc-connect-1
      - mc-connect-2
      - mc-haproxy

  # HAProxy for Load Balancing
  mc-haproxy:
    image: haproxy:2.4
    container_name: mc-haproxy-container
    expose:
      - '6666'
      - '7777'
      - '5555'
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - mc-network
    depends_on:
      - mc-connect-1
      - mc-connect-2

  # Citus Master Node
  mc-citusdata-postgres-master:
    image: citusdata/citus:12.1
    container_name: mc-citusdata-postgres-master
    expose:
      - 5432
    labels:
      - "com.citusdata.role=Master"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./mc/mc-citusdata-postgres-master-data:/var/lib/postgresql/data 777# Updated volume name
      - ./startup_files/postgres-init:/docker-entrypoint-initdb.d:ro
    networks:
      - mc-network

  # pgAdmin for PostgreSQL Management
  mc-pgadmin:
    image: dpage/pgadmin4
    container_name: mc-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mc.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    volumes:
      - ./mc/mc-pgadmin-data:/var/lib/pgadmin
    networks:
      - mc-network
    depends_on:
      - mc-citusdata-postgres-master

volumes:
  mc-citusdata-postgres-master-data:
    driver: local
    driver_opts:
      device: ./mc/mc-citusdata-postgres-master-data
      o: bind
  mc-pgadmin-data:
    driver: local
    driver_opts:
      device: ./mc/mc-pgadmin-data
      o: bind
  mc-connect-1-appdata:
    driver: local
    driver_opts:
      device: ./mc/mc-connect-1-appdata
      o: bind
  mc-connect-1-custom-extensions:
    driver: local
    driver_opts:
      device: ./mc/mc-connect-1-custom-extensions
      o: bind
  mc-connect-1-custom-lib:
    driver: local
    driver_opts:
      device: ./mc/mc-connect-1-custom-lib
      o: bind
  mc-connect-2-appdata:
    driver: local
    driver_opts:
      device: ./mc/mc-connect-2-appdata
      o: bind
  mc-connect-2-custom-extensions:
    driver: local
    driver_opts:
      device: ./mc/mc-connect-2-custom-extensions
      o: bind
  mc-connect-2-custom-lib:
    driver: local
    driver_opts:
      device: ./mc/mc-connect-2-custom-lib
      o: bind

networks:
  mc-network:
    driver: bridge
